language: c

os: linux
dist: trusty

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq git build-essential chrpath diffstat libncurses5-dev texinfo python2.7

script: ./scripts/bitbake-pigaragedoor.sh
